data observation_period_taf(keep=
person_id
observation_period_start_date
observation_period_end_date);
set
tafr14.demog_elig_dates
tafr15.demog_elig_dates
tafr16.demog_elig_dates;
person_id=bene_id;
observation_period_start_date=enrlmt_start_dt;
observation_period_end_date=enrlmt_end_dt;
run;

